### ISSUE TITLE
Error on CPU that may not be an error

### ISSUE THREAD

**Issue by AndrasEros** [n-s-f/hierarchical-rnn#5]
I'm getting this error while running the example regression. It seems CPU is not supported, but unfortunately my GPUs are busy. Can you confirm GPU use only?
And once I'm here, I would like to ask about TF compatibility: which versions are known as compatible? I'm on TF 1.2.0 that may cause the issue.

`InternalError (see above for traceback): Blas GEMM launch failed : a.shape=(10, 61), b.shape=(61, 121), m=10, n=121, k=61
         [[Node: scan/while/multi_hmlstm_cell/cell_0/cell_0/hmlstm_cell/hmlstm_cell/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](scan/while/multi_hmlstm_cell/cell_0/cell_0/hmlstm_cell/hmlstm_cell/concat, scan/while/multi_hmlstm_cell/cell_0/cell_0/hmlstm_cell/hmlstm_cell/MatMul/Enter)]]
         [[Node: Mean/_39 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_3687_Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]`

**Comment by AndrasEros** [comment]
OK, Sorry for my stupidity, I understand that this works with GPU only and 1.2.0 is supported. Thanks for the implementation!

**Comment by nsfinkelstein** [comment]
@AndrasEros Thanks for the comment.  I actually had no trouble running it on CPUs with `tensorflow` installed. I assume it's trying to use the GPUs because you have `tensorflow-gpu` installed. I'm sure you can direct it to use the CPUs anyway, but that would take a little work on your part - I didn't mess with that at all.

Thanks!
